/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FormsBasicFormRouteImport } from './routes/forms/basic-form'
import { Route as FormsSubmitBasicFormIdRouteImport } from './routes/forms-submit/$basicFormId'

const FormsBasicFormRoute = FormsBasicFormRouteImport.update({
  id: '/forms/basic-form',
  path: '/forms/basic-form',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsSubmitBasicFormIdRoute = FormsSubmitBasicFormIdRouteImport.update({
  id: '/forms-submit/$basicFormId',
  path: '/forms-submit/$basicFormId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/forms-submit/$basicFormId': typeof FormsSubmitBasicFormIdRoute
  '/forms/basic-form': typeof FormsBasicFormRoute
}
export interface FileRoutesByTo {
  '/forms-submit/$basicFormId': typeof FormsSubmitBasicFormIdRoute
  '/forms/basic-form': typeof FormsBasicFormRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/forms-submit/$basicFormId': typeof FormsSubmitBasicFormIdRoute
  '/forms/basic-form': typeof FormsBasicFormRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/forms-submit/$basicFormId' | '/forms/basic-form'
  fileRoutesByTo: FileRoutesByTo
  to: '/forms-submit/$basicFormId' | '/forms/basic-form'
  id: '__root__' | '/forms-submit/$basicFormId' | '/forms/basic-form'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  FormsSubmitBasicFormIdRoute: typeof FormsSubmitBasicFormIdRoute
  FormsBasicFormRoute: typeof FormsBasicFormRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/forms/basic-form': {
      id: '/forms/basic-form'
      path: '/forms/basic-form'
      fullPath: '/forms/basic-form'
      preLoaderRoute: typeof FormsBasicFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms-submit/$basicFormId': {
      id: '/forms-submit/$basicFormId'
      path: '/forms-submit/$basicFormId'
      fullPath: '/forms-submit/$basicFormId'
      preLoaderRoute: typeof FormsSubmitBasicFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  FormsSubmitBasicFormIdRoute: FormsSubmitBasicFormIdRoute,
  FormsBasicFormRoute: FormsBasicFormRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
